# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nasa-API-Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nasa-API-Project
pod 'Alamofire', '~> 5.2'

end
